language: c
matrix:
    include:
        - compiler: clang
            os: osx
            env: ARCH=native
        - compiler: gcc
            os: osx
            env: ARCH=native
        - compiler: clang
            os: linux
            env: ARCH=native
        - compiler: gcc
            os: linux
            env: ARCH=native

before_install:
 - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
 - sudo apt-get update -qq
 - sudo apt-get install cmake

script: mkdir build && cd build && cmake .. && make && make test
